# Generated by Django 6.1 on 2026-08-15 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal')], default='daily', max_length=10, verbose_name='Frecuencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('completed', models.BooleanField(default=False, verbose_name='Cumplido')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Registro de hábito',
                'verbose_name_plural': 'Registros de hábitos',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
